services:

    BenTools\CrontabBundle\Command\CrontabUpdateCommand:
        class: BenTools\CrontabBundle\Command\CrontabUpdateCommand
        arguments:
            - '@BenTools\CrontabBundle\CrontabGenerator'
            - '%bentools_crontab.dist_file%'
        tags:
            - { name: console.command }

    BenTools\CrontabBundle\CrontabGenerator:
        class: BenTools\CrontabBundle\CrontabGenerator
        arguments:
            - '@service_container'
