name: CI Workflow

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master]

jobs:

    tests:
        runs-on: ubuntu-20.04
        strategy:
            max-parallel: 10
            matrix:
                php:
                  - '7.3'
                  - '7.4'
                  - '8.0'
                dependency-version: [prefer-lowest, prefer-stable]
                exclude:
                  - php: '8.0'
                    dependency-version: 'prefer-lowest'

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Cache dependencies
            uses: actions/cache@v2
            with:
              path: ~/.composer/cache/files
              key: dependencies-php-${{ matrix.php }}-composer-${{ matrix.dependency-version }}-${{ hashFiles('composer.json') }}

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: ${{ matrix.php }}

          - name: Install dependencies
            run: |
              composer install --prefer-dist --no-interaction --no-suggest

          - name: Update dependencies with ${{ matrix.dependency-version }}
            run: |
              composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

          - name: Execute tests
            run: vendor/bin/pest
